# Generated by Django 5.2.8 on 2026-02-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hairstyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Назва (англійською)')),
                ('description', models.TextField(verbose_name='Опис')),
                ('category', models.CharField(choices=[('men', 'Чоловіча'), ('women', 'Жіноча'), ('unisex', 'Унісекс')], default='unisex', max_length=20, verbose_name='Категорія')),
                ('image', models.ImageField(upload_to='hairstyles/', verbose_name='Зображення')),
                ('master_count', models.IntegerField(default=0, verbose_name='Кількість майстрів')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Зачіска',
                'verbose_name_plural': 'Зачіски',
                'ordering': ['-master_count'],
            },
        ),
        migrations.CreateModel(
            name='FaceShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва форми обличчя')),
                ('description', models.TextField(verbose_name='Опис')),
                ('suitable_hairstyles', models.ManyToManyField(related_name='suitable_for_shapes', to='hairstyles.hairstyle', verbose_name='Підходящі зачіски')),
            ],
            options={
                'verbose_name': 'Форма обличчя',
                'verbose_name_plural': 'Форми обличчя',
            },
        ),
    ]
