# Generated by Django 5.2.8 on 2026-02-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairstyles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairstyle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hairstyles/', verbose_name='Зображення'),
        ),
    ]
