# Generated by Django 5.2.8 on 2026-02-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairstyles', '0002_alter_hairstyle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairstyle',
            name='overlay_image',
            field=models.ImageField(blank=True, help_text='PNG з прозорістю для накладання на фото користувача', null=True, upload_to='hairstyles/overlays/', verbose_name='Оверлей для примірки (PNG)'),
        ),
    ]
