[build]
builder = "nixpacks"

[build.env]
DJANGO_SETTINGS_MODULE = "styleai_project.settings"

[deploy]
startCommand = "python manage.py migrate && python manage.py populate_hairstyles && python manage.py add_10_masters --replace --force-photo && python manage.py download_master_photos && python manage.py assign_master_photos && python manage.py collectstatic --noinput && gunicorn styleai_project.wsgi:application --bind 0.0.0.0:$PORT"
restartPolicyType = "on_failure"