# Generated by Django 5.2.8 on 2026-02-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='priority',
            field=models.CharField(blank=True, help_text='What is most important: Practicality, Style, etc.', max_length=50),
        ),
    ]
