# Generated by Django 6.0.2 on 2026-02-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_quizresult_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='clients_count',
            field=models.PositiveIntegerField(default=0, help_text='Кількість клієнтів'),
        ),
        migrations.AddField(
            model_name='master',
            name='specialty',
            field=models.CharField(blank=True, help_text='e.g. Барбер-стиліст, Стиліст-колорист', max_length=100),
        ),
        migrations.AlterField(
            model_name='master',
            name='experience',
            field=models.CharField(help_text='e.g. 8 років досвіду', max_length=100),
        ),
    ]
