# Generated by Django 5.2.8 on 2026-02-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairstyles', '0002_alter_hairstyle_image'),
        ('masters', '0003_alter_master_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='barber',
            name='styles',
            field=models.ManyToManyField(blank=True, related_name='barbers', to='hairstyles.hairstyle'),
        ),
        migrations.AlterField(
            model_name='barber',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='barbers/'),
        ),
        migrations.AlterField(
            model_name='barber',
            name='specialization',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
