# Generated by Django 5.2.8 on 2026-02-20 21:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairstyles', '0003_add_overlay_image'),
        ('masters', '0004_barber_city_barber_styles_alter_barber_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='default_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ціна за стрижку (грн)'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name="Ім'я клієнта")),
                ('client_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time_slot', models.CharField(max_length=5, verbose_name='Час')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ціна (грн)')),
                ('status', models.CharField(choices=[('pending', 'Очікує підтвердження'), ('confirmed', 'Підтверджено'), ('cancelled', 'Скасовано')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hairstyle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='hairstyles.hairstyle', verbose_name='Тип стрижки')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='masters.master', verbose_name='Майстер')),
            ],
            options={
                'verbose_name': 'Запис',
                'verbose_name_plural': 'Записи',
                'ordering': ['date', 'time_slot'],
            },
        ),
    ]
