# Generated by Django 5.2.8 on 2026-02-25 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_booking_and_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='masters/gallery/', verbose_name='Фото')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Підпис')),
                ('is_work', models.BooleanField(default=True, verbose_name='Робота (портфоліо)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_photos', to='masters.master', verbose_name='Майстер')),
            ],
            options={
                'verbose_name': 'Фото майстра',
                'verbose_name_plural': 'Фото майстрів (галерея)',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
