# Generated by Django 5.2.8 on 2026-03-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_master_photo_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barbershop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='barbershops/', verbose_name='Логотип')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Адреса')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Місто')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Барбершоп-партнер',
                'verbose_name_plural': 'Барбершопи-партнери',
                'ordering': ['name'],
            },
        ),
    ]
