# Generated by Django 5.2.8 on 2026-03-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_barbershop'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адреса / Барбершоп'),
        ),
    ]
