# Generated by Django 5.2.8 on 2026-03-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0008_master_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва')),
                ('icon', models.CharField(blank=True, help_text='Наприклад: fas fa-cut', max_length=50, verbose_name='Іконка (CSS клас)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Послуга',
                'verbose_name_plural': 'Послуги',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='master',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='masters_offering', to='masters.service', verbose_name='Послуги'),
        ),
    ]
