# Generated by Django 5.2.8 on 2026-03-19 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hairstyles', '0003_add_overlay_image'),
        ('masters', '0010_booking_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='hairstyle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='hairstyles.hairstyle', verbose_name='Тип стрижки'),
        ),
    ]
