# Generated by Django 5.2.8 on 2026-03-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0011_alter_booking_hairstyle'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='client_chat_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Client Telegram Chat ID'),
        ),
        migrations.AddField(
            model_name='master',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Telegram Chat ID'),
        ),
    ]
