# Generated by Django 5.2.8 on 2026-03-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0012_booking_client_chat_id_master_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='level',
            field=models.CharField(choices=[('top', 'Топ-майстер'), ('average', 'Середній майстер')], default='average', max_length=20, verbose_name='Рівень майстра'),
        ),
    ]
