# Generated by Django 5.2.8 on 2026-02-12 10:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hairstyles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='user_photos/', verbose_name='Фото користувача')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('face_shape', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hairstyles.faceshape', verbose_name='Форма обличчя')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Фото користувача',
                'verbose_name_plural': 'Фото користувачів',
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Рівень впевненості')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hairstyle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='hairstyles.hairstyle')),
                ('user_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='styleai.userphoto')),
            ],
            options={
                'verbose_name': 'Рекомендація AI',
                'verbose_name_plural': 'Рекомендації AI',
                'ordering': ['-confidence_score'],
            },
        ),
    ]
