# Generated by Django 5.2.8 on 2026-02-16 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styleai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HairSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hair_type', models.CharField(blank=True, choices=[('straight', 'Пряме'), ('wavy', 'Хвилясте'), ('curly', 'Кучеряве'), ('coily', 'Сильно кучеряве'), ('thin', 'Тонке'), ('thick', 'Густе')], max_length=20, verbose_name='Тип волосся')),
                ('lifestyle', models.CharField(blank=True, choices=[('active', 'Активний (спорт, рух)'), ('office', 'Офісний / діловий'), ('creative', 'Креативний / творчий'), ('minimal', 'Мінімальний догляд'), ('casual', 'Повсякденний')], max_length=20, verbose_name='Спосіб життя')),
                ('covers_ears', models.BooleanField(default=False, verbose_name='Закривати вуха')),
                ('long_hairstyle', models.BooleanField(default=False, verbose_name='Подовжена зачіска')),
                ('short_hairstyle', models.BooleanField(default=False, verbose_name='Коротка стрижка')),
                ('low_maintenance', models.BooleanField(default=False, verbose_name='Мінімум догляду')),
                ('volume', models.BooleanField(default=False, verbose_name="Об'єм")),
                ('notes', models.TextField(blank=True, verbose_name='Додаткові побажання')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Опитування зачіски',
                'verbose_name_plural': 'Опитування зачісок',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='userphoto',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_photos', to='styleai.hairsurvey', verbose_name='Опитування'),
        ),
    ]
