# Generated by Django 5.2.8 on 2026-03-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styleai', '0002_hairsurvey_userphoto_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='userphoto',
            name='predicted_gender',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Стать (AI)'),
        ),
    ]
