# Generated by Django 6.0.2 on 2026-03-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styleai', '0003_userphoto_predicted_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairsurvey',
            name='care_time_extra',
            field=models.CharField(blank=True, max_length=20, verbose_name='Час на догляд (з опитування)'),
        ),
        migrations.AddField(
            model_name='hairsurvey',
            name='face_shape_extra',
            field=models.CharField(blank=True, max_length=20, verbose_name='Форма обличчя (з опитування)'),
        ),
        migrations.AddField(
            model_name='hairsurvey',
            name='hair_length_extra',
            field=models.CharField(blank=True, max_length=20, verbose_name='Довжина волосся (з опитування)'),
        ),
        migrations.AddField(
            model_name='hairsurvey',
            name='priority_extra',
            field=models.CharField(blank=True, max_length=20, verbose_name='Пріоритет (з опитування)'),
        ),
    ]
